### ISSUE TITLE
Filter duplicated messages

### ISSUE THREAD

**Issue by rogeriocsilva** [kreuzerk/primeNG-advanced-growl#13]
Help with noob question :p

Is there a way to prevent duplicated messages? 

I wan't to prevent certain duplicated messages, i.e, before creating a new error message,i want to verify if is any duplicated message onscreen, but i don't want this approach for info messages.

**Comment by rogeriocsilva** [comment]
Oh, and i want to add an event to the message, for example when i click the message print something

**Comment by kreuzerk** [comment]
Hi @rogeriocsilva. Thanks a lot for your feedback. 

- Unfortunately I do not know a Rx Operator that does what you want out of the box. I would take another approach. I would split the message Stream up in 2 Streams. So you would end up with a stream of distinct error messages and a stream of all other messages. You are then able to merge those streams together. I have created a small JSBin that should more clearly illustrate what I tried to explain here. http://jsbin.com/hikokolumu/edit?js,console

I am still thinking of a useful API to provide this feature in the library. Maybe an optional parameter on the service method that allows you to only have distinct messages of a specific type. I will have to inspect this further. And of course Ideas and Pull Request are welcome ;)

- I am working on the second point. The idea is that the library throws an event when a click on a message happened.

**Comment by rogeriocsilva** [comment]
Thanks for the reply, i think there's a misunderstanding here.
I don't want to filter the stream, o want to filter the array on the component. With primeng growl i could see if the message was on the array, which meant the message still was on screen, so i didn't put a duplicated message on screen. But as you say primeng messages don't have unique lifetime, so i wanted to try your wrapper.

**Comment by kreuzerk** [comment]
Ah okay. In that case you can just use the wrapper without passing a lifetime. Then everything becomes easier as we do not have so much async stuff going on. In that case you can directly filter the array inside the do operator.

**Comment by rogeriocsilva** [comment]
Ok i think i got a way to do it. Making an EventEmitter to see the changes on messages array, so i can always check if its still something on screen and then only create a new message if i want to. Thanks for the help.

**Comment by kreuzerk** [comment]
Great job! I have created a PR for the missing click functionality. Please find the Releasenotes here: https://github.com/kreuzerk/primeNG-advanced-growl/releases/tag/v2.0.0

I will close this issue if it is ok for you. Thank you for your help!!

**Comment by rogeriocsilva** [comment]
Yeah sure, think about adding `@Output() onMessagesChanges = new EventEmitter<Array<AdvPrimeMessage>>();`. It's very usefull to know what is on screen and what is not, before creating a new growl. Thank you for your help! :D

**Comment by kreuzerk** [comment]
Yes I will definitely think about that. If you already have a working solution you are also welcome to create a PR.

**Comment by rogeriocsilva** [comment]
I got a another workaround, and now i feel like my PR is useless.

```
import { AdvGrowlComponent } from 'primeng-advanced-growl/lib/messages/adv-growl.component';
import { ViewChild } from '@angular/core';

export class AppComponent {
    @ViewChild(AdvGrowlComponent)
    private growlComponent: AdvGrowlComponent;

    public createError(err: string): void {
      var index = this.growlComponent.messages.findIndex(message => message.detail === err);
      if(index>=0){
        this.growlComponent.removeMessage(this.growlComponent.messages[index].id);
      }
      this.advGrowlService.createErrorMessage(err,'Something went wrong!');
    }
}

```
I did this so i cannot have duplicated error messages, but refresh their life time. 
I'm sorry x)
