### ISSUE TITLE
build error as soon as install AdvGrowl

### ISSUE THREAD

**Issue by changhuixu** [kreuzerk/primeNG-advanced-growl#173]
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/font-awesome/css/font-awesome.min.css
Module build failed: Error: Cannot find module 'cuint'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
****
**********
@ ./node_modules/primeng/resources/themes/omega/theme.css 4:14-129
 @ multi ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/primeng/resources/themes/omega/theme.css ./node_modules/primeng/resources/primeng.min.css ./src/styles.css
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/font-awesome/css/font-awesome.min.css
Module build failed: Error: Cannot find module 'cuint'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)

@ ./node_modules/primeng/resources/primeng.min.css 4:14-123
 @ multi ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/primeng/resources/themes/omega/theme.css ./node_modules/primeng/resources/primeng.min.css ./src/styles.css

**Comment by changhuixu** [comment]
Is just me or??? I have tried AdvGrowl v3.1.3 and v3.1.0, both failed to build after npm install.

The error looks like due to css loader. 
Styles section in cli config
"styles": [
            "../node_modules/font-awesome/css/font-awesome.min.css",
            "../node_modules/primeng/resources/themes/omega/theme.css",
            "../node_modules/primeng/resources/primeng.min.css",
            "styles.css"
        ],

**Comment by kreuzerk** [comment]
Hey @changhuixu. Thanks for mentioning this issues. Unfortunately I am unable to reproduce this issue. I have just tried to install primeng-advanced-growl 3.1.3 with an Angular CLI 1.6.2. Everything works fine. Which CLI Version do you use?

**Comment by kreuzerk** [comment]
I just tried it with the newest CLI version 1.6.4. Same result. Everything works. Can you maybe provide more informations on your project setup (CLI Version etc...)?

**Comment by changhuixu** [comment]
Thank you for your response. It was caused by my cli versions. One of my PC has an old version of angular-cli installed...
After I cleaned angular cli, everything works.

**Comment by kreuzerk** [comment]
Great! Glad to hear that it worked
