### ISSUE TITLE
Import of whole primeng lib

### ISSUE THREAD

**Issue by KreutzerPh** [kreuzerk/primeNG-advanced-growl#186]
Hello,

We detect a problem during the importation of the following line :
  * import {GrowlModule} from 'primeng/primeng';

in module src/app/lib/adv-growl.module.ts. The whole primeng library is loaded in the project instead of only the single growl component.

A fix possibility is :
 * import { GrowlModule } from 'primeng/growl';

Could you please fix it in a new version ?

Thanks in advance
Philippe

**Comment by kreuzerk** [comment]
@KreutzerPh Thanks a lot for submitting this issue. I think that you already found the issue. I will apply your fix and release a new version.

It may take a day or two as I am pretty busy at the moment ;) I will let you know when I have released the new version. Thanks a lot for bringing up this issue.

**Comment by kreuzerk** [comment]
I have deployed version 3.1.4. Your issue should be fixed with this version. Let me know if not.
Thanks again for using this library and submitting the issue.
