### ISSUE TITLE
Compatibility with Angular and RxJS 6

### ISSUE THREAD

**Issue by sebaiona** [kreuzerk/primeNG-advanced-growl#200]
Hi @kreuzerk ,

I updated my project and unfortunately Angular 5.0.0 is in `primeng-advanced-growl` dependencies so that I can't use it anymore...
Is there a possibility to update the package to be compatible with `Angular `and `RxJS` 6 ?
(You could use rxjs-compat in a first time to avoid problems with rxjs 6)

Thanks in advance.

**Comment by sebaiona** [comment]
@kreuzerk Thank you for considering this.
As I am myself quite busy and in the rush for a project, I'll see if I can do something but I'm not sure at all...

**Comment by sebaiona** [comment]
Hi !
Did you have time to have a look on this problem ?
On my side, I couldn't check anything...

**Comment by kreuzerk** [comment]
Hi @sebaiona 
Unfortunately I was unable to find time to apply a fix. I am quite busy at the moment and don't know when I will find time to update the project.

**Comment by michaelstievenart** [comment]
This would be a great feature as the package is no longer useable for Angular 6+ where the new rxjs is used.

**Comment by kreuzerk** [comment]
Hi guys! Sorry that it took me so long to update the project to be Angular 6 and Rx 6 compatible. But I was really busy in the last month. Moments ago I have published a new package 4.0.2 - This package should now work with Angular and Rx 6. 

Please note that I published the package from my local machine. **The sources in GitHub are not up to date yet**. I am now using Angular CLI to package the library. Therefore I need to adjust the project structure etc... I am working on it and will upload the sources as soon as possible. But the published library should already work. 

Feedback welcome!

**Comment by michaelstievenart** [comment]
That's awesome, thanks for the great work!
