### ISSUE TITLE
Pause messages on hover

### ISSUE THREAD

**Issue by kreuzerk** [kreuzerk/primeNG-advanced-growl#22]

**Comment by kreuzerk** [comment]
@rogeriocsilva As you brought up this issue I thought you might be interested in the PR I have created https://github.com/kreuzerk/primeNG-advanced-growl/pull/23. It is not yet perfect. There are some tradeoffs I had to make to get this working.

- With this PR you can pass a flag (freezeMessagesOnHover) to the library. If set to true all messages are freezed while you hover over them.

There are still the following problems:
- Lets say you have 2 or 3 messages that all appeared at a different time and you hover over one of them. What happens is that all of them are freezed. As soon as your mouse moves a message the messages will all disappear after the lifetime you specified. 
- The problem is that we currently have no way of getting the messageID on hover. Or at least I do not know a way to achieve this. Maybe you have an idea? I think if we would be able to get the messageId on hover we are able to pause exactly the hovered message.

I still think that even with those tradeoffs this feature is very useful.

**Comment by rogeriocsilva** [comment]
Hey, sorry for answering this late but i had no time to test this.
Since i'm not comfortable with rxjs i won't much as a help, i can only test it.
When i get time i'll try to give some feedback.

**Comment by kreuzerk** [comment]
No problem. Thanks a lot. I am looking forward to your feedback. To even optimize this feature I have created a PR at primeng (https://github.com/primefaces/primeng/pull/3842) to get the message on hover.
